repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle
        language: system
        entry: java -jar ./tools/checkstyle-10.18.1-all.jar -c ./checkstyle.xml
        types: [java]
        pass_filenames: true
        # opcional: args: ["-f", "plain"]