services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kc_user
      POSTGRES_PASSWORD: kc_pass
    volumes:
      - kc-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kc_user -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - start
      - --hostname=localhost
      - --hostname-strict=false
      - --proxy-headers=xforwarded
      - --http-enabled=true
      - --http-port=8080
      - --http-relative-path=/kc
      - --import-realm
      - --optimized
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: kc_user
      KC_DB_PASSWORD: kc_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./resource-server/keycloak/realms:/opt/keycloak/data/import:ro
    expose:
      - "8080"
    restart: unless-stopped

  resource-server:
    build:
      context: ./resource-server
    environment:
      SPRING_PROFILES_ACTIVE: local
    expose:
      - "8080"
    restart: unless-stopped

  gateway:
    image: nginx:1.27-alpine
    depends_on:
      - keycloak
      - resource-server
    ports:
      - "8443:443"
    volumes:
      - ./nginx/gateway.local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/includes:/etc/nginx/includes:ro
      - ./resource-server/static:/usr/share/nginx/html:ro
      - ./certs/out:/etc/nginx/tls:ro
    restart: unless-stopped

volumes:
  kc-pg: