services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kc_user
      POSTGRES_PASSWORD: kc_pass
    volumes:
      - kc-pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kc_user -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - start
      - --http-enabled=true
      - --http-port=8080
      - --https-port=8443
      - --https-key-store-file=/opt/keycloak/conf/server.keystore
      - --https-key-store-password=$KEYSTORE_PASSWORD
      - --https-key-store-type=PKCS12
      - --http-relative-path=/kc
      - --hostname=http://localhost/kc
      - --hostname-strict=true
      - --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: kc_user
      KC_DB_PASSWORD: kc_pass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import:ro
      - ./keycloak/conf:/opt/keycloak/conf:ro
    expose:
      - "8080"
      - "8443"
    restart: unless-stopped

  api_gateway:
    build: .
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/api/actuator/health | grep -q '\"status\":\"UP\"'" ]
    
      interval: 30s
      timeout: 5s
      retries: 10
    expose:
      - "8080"
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - keycloak
      - api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

volumes:
  kc-pg: