spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}
          issuer-uri: ${JWT_ISSUER_URI:}
app:
  security:
    expected-issuer: ${EXPECTED_ISSUER}
    expected-audience: ${EXPECTED_AUDIENCE:resource-api}
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /api/actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never